import assert from 'node:assert/strict'; import {mkdtempSync,mkdirSync,readFileSync,readdirSync,rmSync,writeFileSync} from 'node:fs'; import {join} from 'node:path'; import {createRequire} from 'node:module'; import {Readable} from 'node:stream'; import {createHash} from 'node:crypto'; const require=createRequire(import.meta.url); const {compareVersions,validateManifest,readResponseJson,downloadInstaller,parseContentRange}=require('../../electron/app-updater.cjs');
const testTempRoot = join(process.cwd(), '.test-tmp-v063', '1788114714459-' + process.pid); mkdirSync(testTempRoot,{recursive:true}); const localTemp = prefix => mkdtempSync(join(testTempRoot, prefix + '-')); process.once('exit',()=>{try{rmSync(testTempRoot,{recursive:true,force:true})}catch{}});
assert.equal(compareVersions('0.4.0', '0.3.9'), 1);
assert.equal(compareVersions('0.4.0', '0.4.0'), 0);
const validUpdateManifest = { schemaVersion: 1, version: '0.4.1', asset: 'NAI-Prompt-Studio-V5-Setup-0.4.1.exe', url: 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.4.1/NAI-Prompt-Studio-V5-Setup-0.4.1.exe', size: 4096, sha512: 'a'.repeat(128), releaseNotes: 'Fixture' };
assert.equal(validateManifest(validUpdateManifest, '0.4.0').available, true);
assert.equal(validateManifest({ ...validUpdateManifest, version: '0.3.9' }, '0.4.0').available, false);
assert.throws(() => validateManifest({ ...validUpdateManifest, version: 'latest' }, '0.4.0'), /invalid semantic version/i);
assert.throws(() => validateManifest({ ...validUpdateManifest, url: 'https://example.com/NAI-Prompt-Studio-V5-Setup-0.4.1.exe' }, '0.4.0'), /host is not trusted/i);
assert.throws(() => validateManifest({ ...validUpdateManifest, sha512: 'invalid' }, '0.4.0'), /SHA-512/i);
assert.deepEqual(parseContentRange('bytes 10-20/42'), { start: 10, end: 20, total: 42 });
assert.equal(parseContentRange('bytes 10-/42'), null);

function mockedResponse(chunks, statusCode = 200, headers = {}, complete = true) {
  const response = Readable.from(chunks);
  response.statusCode = statusCode;
  response.headers = Object.fromEntries(Object.entries(headers).map(([key, value]) => [key.toLowerCase(), String(value)]));
  response.complete = complete;
  return response;
}
function updateFixture(bytes = 4096) {
  const payload = Buffer.alloc(bytes, 73);
  return { payload, manifest: { available: true, schemaVersion: 1, version: '0.5.6', asset: 'NAI-Prompt-Studio-V5-Setup-0.5.6.exe', url: 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.6/NAI-Prompt-Studio-V5-Setup-0.5.6.exe', size: payload.length, sha512: createHash('sha512').update(payload).digest('hex'), releaseNotes: 'Fixture' } };
}
const manifestStall = new Readable({ read() {} });
manifestStall.complete = false;
await assert.rejects(readResponseJson(manifestStall, 1024, { idleTimeoutMs: 5 }), /manifest response stalled/i);
const manifestAbortController = new AbortController();
const manifestAbort = new Readable({ read() {} });
manifestAbort.complete = false;
const manifestAbortPromise = readResponseJson(manifestAbort, 1024, { idleTimeoutMs: 1000, signal: manifestAbortController.signal });
manifestAbortController.abort();
await assert.rejects(manifestAbortPromise, error => error?.code === 'ABORT_ERR');
const updateTemp = localTemp('nai-update');
const normalFixture = updateFixture();
const normalProgress = [];
const normalTarget = await downloadInstaller(normalFixture.manifest, updateTemp, { requestImpl: async () => mockedResponse([normalFixture.payload]), onProgress: event => normalProgress.push(event), retryDelayMs: 0 });
assert.equal(readFileSync(normalTarget).equals(normalFixture.payload), true);
assert.equal(normalProgress.at(-1).phase, 'ready');
assert.equal(normalProgress.at(-1).percent, 100);
rmSync(normalTarget, { force: true });
const resumeFixture = updateFixture();
const resumePartial = join(updateTemp, resumeFixture.manifest.asset + '.partial');
const resumeSplit = 1300;
writeFileSync(resumePartial, resumeFixture.payload.subarray(0, resumeSplit));
const resumeHeaders = [];
let resumeAttempt = 0;
await downloadInstaller(resumeFixture.manifest, updateTemp, { maxAttempts: 2, retryDelayMs: 0, requestImpl: async (_url, request) => {
  resumeHeaders.push(request.headers?.Range || '');
  resumeAttempt += 1;
  if (resumeAttempt === 1) return mockedResponse([resumeFixture.payload.subarray(resumeSplit, resumeSplit + 700)], 206, { 'content-range': `bytes ${resumeSplit}-${resumeSplit + 699}/${resumeFixture.manifest.size}`, 'content-length': 700 }, false);
  const start = Number(String(request.headers?.Range || '').match(/(\d+)/)?.[1] ?? resumeSplit);
  return mockedResponse([resumeFixture.payload.subarray(start)], 206, { 'content-range': `bytes ${start}-${resumeFixture.manifest.size - 1}/${resumeFixture.manifest.size}`, 'content-length': resumeFixture.manifest.size - start });
} });
assert.deepEqual(resumeHeaders, [`bytes=${resumeSplit}-`, `bytes=${resumeSplit + 700}-`]);
assert.equal(readFileSync(join(updateTemp, resumeFixture.manifest.asset)).equals(resumeFixture.payload), true);
const restartFixture = updateFixture();
restartFixture.manifest.version = '0.5.7';
restartFixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.7.exe';
restartFixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.7/NAI-Prompt-Studio-V5-Setup-0.5.7.exe';
const restartPartial = join(updateTemp, restartFixture.manifest.asset + '.partial');
writeFileSync(restartPartial, Buffer.alloc(200, 1));
let restartRange = '';
await downloadInstaller(restartFixture.manifest, updateTemp, { requestImpl: async (_url, request) => { restartRange = request.headers?.Range || ''; return mockedResponse([restartFixture.payload]); } });
assert.equal(restartRange, 'bytes=200-');
assert.equal(readFileSync(join(updateTemp, restartFixture.manifest.asset)).equals(restartFixture.payload), true);
const complete416Fixture = updateFixture();
complete416Fixture.manifest.version = '0.5.8';
complete416Fixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.8.exe';
complete416Fixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.8/NAI-Prompt-Studio-V5-Setup-0.5.8.exe';
const complete416Partial = join(updateTemp, complete416Fixture.manifest.asset + '.partial');
writeFileSync(complete416Partial, complete416Fixture.payload);
let complete416Calls = 0;
await downloadInstaller(complete416Fixture.manifest, updateTemp, { forceRangeRequest: true, requestImpl: async (_url, request) => { complete416Calls += 1; assert.equal(request.headers.Range, `bytes=${complete416Fixture.manifest.size}-`); return mockedResponse([], 416); } });
assert.equal(complete416Calls, 1);
assert.equal(readFileSync(join(updateTemp, complete416Fixture.manifest.asset)).equals(complete416Fixture.payload), true);
const invalid416Fixture = updateFixture();
invalid416Fixture.manifest.version = '0.5.13';
invalid416Fixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.13.exe';
invalid416Fixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.13/NAI-Prompt-Studio-V5-Setup-0.5.13.exe';
const invalid416Partial = join(updateTemp, invalid416Fixture.manifest.asset + '.partial');
writeFileSync(invalid416Partial, invalid416Fixture.payload.subarray(0, 100));
await assert.rejects(downloadInstaller(invalid416Fixture.manifest, updateTemp, { maxAttempts: 1, requestImpl: async () => mockedResponse([], 416) }), /incomplete resume range/i);
assert.equal(readdirSync(updateTemp).includes(invalid416Fixture.manifest.asset + '.partial'), false);
const malformedFixture = updateFixture();
malformedFixture.manifest.version = '0.5.9';
malformedFixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.9.exe';
malformedFixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.9/NAI-Prompt-Studio-V5-Setup-0.5.9.exe';
const malformedPartial = join(updateTemp, malformedFixture.manifest.asset + '.partial');
writeFileSync(malformedPartial, Buffer.alloc(200, 4));
let malformedCalls = 0;
await downloadInstaller(malformedFixture.manifest, updateTemp, { maxAttempts: 2, retryDelayMs: 0, requestImpl: async () => { malformedCalls += 1; return malformedCalls === 1 ? mockedResponse([Buffer.alloc(10)], 206, { 'content-range': 'bytes 999-1008/4096', 'content-length': 10 }) : mockedResponse([malformedFixture.payload]); } });
assert.equal(malformedCalls, 2);
assert.equal(readFileSync(join(updateTemp, malformedFixture.manifest.asset)).equals(malformedFixture.payload), true);
const timeoutFixture = updateFixture();
timeoutFixture.manifest.version = '0.5.11';
timeoutFixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.11.exe';
timeoutFixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.11/NAI-Prompt-Studio-V5-Setup-0.5.11.exe';
await assert.rejects(downloadInstaller(timeoutFixture.manifest, updateTemp, { maxAttempts: 1, idleTimeoutMs: 5, requestImpl: async () => {
  const response = new Readable({ read() {} }); response.statusCode = 200; response.headers = {}; response.complete = false; return response;
} }), /stalled|premature/i);
const cancelFixture = updateFixture();
cancelFixture.manifest.version = '0.5.12';
cancelFixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.12.exe';
cancelFixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.12/NAI-Prompt-Studio-V5-Setup-0.5.12.exe';
const updateCancelController = new AbortController();
const updateCancelStream = new Readable({ read() { if (!this.sent) { this.sent = true; this.push(cancelFixture.payload.subarray(0, 500)); } } });
updateCancelStream.statusCode = 200; updateCancelStream.headers = {}; updateCancelStream.complete = false;
await assert.rejects(downloadInstaller(cancelFixture.manifest, updateTemp, { signal: updateCancelController.signal, maxAttempts: 1, idleTimeoutMs: 1000, requestImpl: async () => updateCancelStream, onProgress: event => { if (event.phase === 'downloading' && event.completed > 0) updateCancelController.abort(); } }), error => error?.code === 'ABORT_ERR');
assert.equal(readFileSync(join(updateTemp, cancelFixture.manifest.asset + '.partial')).length, 500);
const mismatchFixture = updateFixture();
 mismatchFixture.manifest.version = '0.5.10';
 mismatchFixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.10.exe';
 mismatchFixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.10/NAI-Prompt-Studio-V5-Setup-0.5.10.exe';
await assert.rejects(downloadInstaller({ ...mismatchFixture.manifest, sha512: 'f'.repeat(128) }, updateTemp, { maxAttempts: 1, requestImpl: async () => mockedResponse([mismatchFixture.payload]) }), /size or SHA-512/i);
assert.equal(readdirSync(updateTemp).includes(mismatchFixture.manifest.asset + '.partial'), false);
const fullMismatchFixture = updateFixture();
fullMismatchFixture.manifest.version = '0.5.18';
fullMismatchFixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.18.exe';
fullMismatchFixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.18/NAI-Prompt-Studio-V5-Setup-0.5.18.exe';
writeFileSync(join(updateTemp, fullMismatchFixture.manifest.asset + '.partial'), Buffer.alloc(fullMismatchFixture.manifest.size, 1));
let fullMismatchRange = 'unset';
await downloadInstaller(fullMismatchFixture.manifest, updateTemp, { maxAttempts: 1, requestImpl: async (_url, request) => { fullMismatchRange = request.headers?.Range || ''; return mockedResponse([fullMismatchFixture.payload]); } });
assert.equal(fullMismatchRange, '');
const oversizeFixture = updateFixture();
oversizeFixture.manifest.version = '0.5.14';
oversizeFixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.14.exe';
oversizeFixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.14/NAI-Prompt-Studio-V5-Setup-0.5.14.exe';
await assert.rejects(downloadInstaller(oversizeFixture.manifest, updateTemp, { maxAttempts: 1, requestImpl: async () => mockedResponse([Buffer.concat([oversizeFixture.payload, Buffer.from([1])])]) }), /exceeded the manifest size/i);
assert.equal(readdirSync(updateTemp).includes(oversizeFixture.manifest.asset + '.partial'), false);
const shortFixture = updateFixture();
shortFixture.manifest.version = '0.5.15';
shortFixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.15.exe';
shortFixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.15/NAI-Prompt-Studio-V5-Setup-0.5.15.exe';
await assert.rejects(downloadInstaller(shortFixture.manifest, updateTemp, { maxAttempts: 1, requestImpl: async () => mockedResponse([shortFixture.payload.subarray(0, 200)]) }), /ended before the manifest size/i);
assert.equal(readFileSync(join(updateTemp, shortFixture.manifest.asset + '.partial')).length, 200);
rmSync(join(updateTemp, shortFixture.manifest.asset + '.partial'), { force: true });
const prematureFixture = updateFixture();
prematureFixture.manifest.version = '0.5.16';
prematureFixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.16.exe';
prematureFixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.16/NAI-Prompt-Studio-V5-Setup-0.5.16.exe';
await assert.rejects(downloadInstaller(prematureFixture.manifest, updateTemp, { maxAttempts: 1, requestImpl: async () => mockedResponse([prematureFixture.payload.subarray(0, 200)], 200, {}, false) }), /prematurely/i);
assert.equal(readFileSync(join(updateTemp, prematureFixture.manifest.asset + '.partial')).length, 200);
rmSync(join(updateTemp, prematureFixture.manifest.asset + '.partial'), { force: true });
const reuseFixture = updateFixture();
reuseFixture.manifest.version = '0.5.17';
reuseFixture.manifest.asset = 'NAI-Prompt-Studio-V5-Setup-0.5.17.exe';
reuseFixture.manifest.url = 'https://github.com/shiza2xx/nai-prompt-studio/releases/download/v0.5.17/NAI-Prompt-Studio-V5-Setup-0.5.17.exe';
const reuseTarget = await downloadInstaller(reuseFixture.manifest, updateTemp, { requestImpl: async () => mockedResponse([reuseFixture.payload]) });
const reuseProgress = [];
assert.equal(await downloadInstaller(reuseFixture.manifest, updateTemp, { requestImpl: async () => { throw new Error('verified target should be reused'); }, onProgress: event => reuseProgress.push(event) }), reuseTarget);
assert.equal(reuseProgress.at(-1).message, 'Verified update already downloaded.');
rmSync(updateTemp, { recursive: true, force: true });

let loaderActive = 0;
let loaderPeak = 0;
const loaderProgress = [];
console.log('release-updater tests passed.');
