import assert from 'node:assert/strict'; import {readFileSync,readdirSync} from 'node:fs'; import {mixCompanionCapacity,mixCompanionScale,mixOrbitLayout} from '../../src/artist-mix-layout.ts'; import * as f from './source-fixtures.mjs'; const {uiSource,customTagsWorkspaceSource,savedLibraryWorkspaceSource,styleSource,typesSource,previewSource,previewCacheSource,metadataHighlightSource,warmupSource,thumbnailSource,storageSource,globalSource,metadataWorkspaceSource,electronSource,customTagLibrarySource,customTagPackSource,componentSource,catalogUpdaterSource,updateV5Source,preloadSource,appPathsSource,indexSource,packageSource,lockSource,tsconfigSource,localEnvSource,localRunnerSource,desktopBuildSource,catalogPacksSource,catalogPacksVersionSource,thinCatalogSource,releaseManifestSource,installerBuildSource,iconPreparationSource,iconResizeSource,installerLauncherSource,installerProofSource,installerProofRunnerSource,installerStorePatchSource,nsisIncludeSource,npmrcSource}=f;
assert.match(uiSource, /selected V5 artist weights/);
assert.match(uiSource, /let startupBusy = false;/);
assert.match(uiSource, /const failure = !startupBusy && startupFailures.length/);
assert.match(uiSource, /startupBusy = true;[^]*?await preloadCards\(failed, 'Retrying failed previews'\)[^]*?startupBusy = false;/);
assert.match(uiSource, /MetadataWorkspace/);
assert.match(uiSource, /new MetadataWorkspace\(\(\) => catalog\.artists\)/);
assert.match(metadataWorkspaceSource, /private readToken = 0;/);
assert.match(metadataWorkspaceSource, /const request = \+\+this\.readToken;/);
assert.match(metadataWorkspaceSource, /import \{ createMetadataDisplayPreview \} from '\.\/metadata-display-preview';/);
assert.match(metadataWorkspaceSource, /const displayBlob = await createMetadataDisplayPreview\(new Blob\(\[bytes\], \{ type: mime \}\)\);\s+if \(request !== this\.readToken\) return;\s+this\.result = result;\s+this\.sourceObjectUrl = URL\.createObjectURL\(displayBlob\);/);
assert.match(metadataWorkspaceSource, /catch \(error\) \{\s+if \(request !== this\.readToken\) return;/);
assert.match(metadataWorkspaceSource, /bindArtistCardPreview\(root\)/);
assert.match(metadataWorkspaceSource, /private renderHighlighted\(value: string\): string/);
assert.match(metadataWorkspaceSource, /const highlighter = this\.artistHighlighter\(\);/);
assert.match(metadataWorkspaceSource, /const escapeHtml = escapeMetadataHtml;/);
assert.match(metadataWorkspaceSource, />IMAGE METADATA</);
assert.match(metadataWorkspaceSource, />Reveal the image's data\.</);
assert.match(metadataWorkspaceSource, />Drop an image here</);
assert.match(metadataWorkspaceSource, /Choose or drop a NovelAI Image\. Analysis stays entirely on this device and never changes your prompt builder\./);
assert.match(metadataWorkspaceSource, /aria-label="Choose a NovelAI image or drop one here"/);
assert.match(metadataWorkspaceSource, /accept="image\/png,\.png,image\/webp,\.webp"/);
assert.match(metadataWorkspaceSource, /Metadata extraction is based on <a href="https:\/\/github\.com\/NovelAI\/novelai-image-metadata" target="_blank" rel="noopener noreferrer">NovelAI's official image metadata repository<\/a>\./);
assert.doesNotMatch(metadataWorkspaceSource, /URL\.createObjectURL\(file\)/, 'metadata display must use the bounded preview blob instead of the original file');
assert.match(metadataWorkspaceSource, /URL\.revokeObjectURL\(this\.sourceObjectUrl\)/);
assert.match(metadataWorkspaceSource, /dispose\(\): void \{\s+this\.deactivate\(\);\s+this\.releaseSourceImage\(\);\s+\}/);
assert.match(metadataWorkspaceSource, /class="metadata-source-image"[\s\S]*?<div class="metadata-model"/);
assert.match(metadataWorkspaceSource, /data-metadata-copy="\$\{index\}"/);
assert.match(metadataWorkspaceSource, /<pre>[\s\S]*?<div class="metadata-prompt-actions">[\s\S]*?>Copy prompt<\/button>/);
assert.match(metadataWorkspaceSource, /private activePrompt\(index: number\): string/);
assert.match(metadataWorkspaceSource, /activeValue \? '' : 'disabled'/);
assert.doesNotMatch(metadataWorkspaceSource, /sourceKind === 'remote' \? \[\]/, 'remote metadata saves must retain catalog-aware artist extraction');
assert.match(uiSource, /metadataWorkspace\.dispose\(\);/);
assert.match(storageSource, /export function loadCustomTags\(\): CustomTag\[\] \{[\s\S]*?if \(!bridge\(\)\) return \[\];/);
assert.match(storageSource, /export async function transactCustomTags/);
assert.doesNotMatch(storageSource.match(/export function saveCustomTags[\s\S]*?\n\}/)?.[0] ?? '', /localStorage\.setItem/);
assert.match(storageSource, /memory-\[a-zA-Z0-9_-\]/);
assert.match(storageSource, /export function normalizeCustomTagPresets\(values: unknown\): CustomTagPreset\[\] \{/);
assert.match(storageSource, /DEFAULT_CUSTOM_TAG_PRESET_ID/);
assert.match(storageSource, /from '\.\/custom-tag-presets\.ts'/);
const savedPromptNormalizerSource = storageSource.match(/export function normalizeSavedPromptSnapshot\(value: unknown\): SavedPromptSnapshot \| undefined \{[\s\S]*?\n\}/)?.[0] ?? '';
assert.match(savedPromptNormalizerSource, /version: 2[\s\S]*?base: draft\.base[\s\S]*?characters: draft\.characters[\s\S]*?randomRange/);
assert.doesNotMatch(savedPromptNormalizerSource, /animationMode/);
const savedPromptTypeSource = typesSource.match(/export interface SavedPromptSnapshot \{[\s\S]*?\n\}/)?.[0] ?? '';
assert.doesNotMatch(savedPromptTypeSource, /animationMode/);
const savedPromptCaptureSource = uiSource.match(/function currentSavedPromptSnapshot\(\): SavedPromptSnapshot \{[\s\S]*?\n\}/)?.[0] ?? '';
assert.match(savedPromptCaptureSource, /JSON\.stringify\(base\)[\s\S]*?characters[\s\S]*?randomRange/);
assert.doesNotMatch(savedPromptCaptureSource, /currentDraft|animationMode/);
assert.equal(tsconfigSource.compilerOptions.allowImportingTsExtensions, true);
assert.match(electronSource, /customTagPresets: \[\]/);
assert.match(electronSource, /custom-tags:transact/);
assert.match(electronSource, /custom-tags:import/); assert.match(electronSource, /custom-tags:export/);
assert.match(customTagLibrarySource, /Refusing to overwrite malformed workspace\.json/);
assert.match(customTagPackSource, /nai-custom-tags-pack/); assert.match(customTagPackSource, /extractFile/); assert.doesNotMatch(customTagPackSource, /extractAll/);
assert.match(preloadSource, /webUtils\.getPathForFile/); assert.match(customTagsWorkspaceSource, /Import \.naipack/); assert.match(customTagsWorkspaceSource, /data-export-preset/); assert.match(customTagsWorkspaceSource, /custom-tag-pack-drop-toast/); assert.match(customTagsWorkspaceSource, /Import a shared Custom Tags preset\./); assert.match(styleSource, /\.custom-tag-pack-drop-toast\[hidden\] \{ display: none; \}/); assert.doesNotMatch(styleSource, /\.custom-tags-workspace\.is-pack-dragging/);
assert.match(styleSource, /\.preset-row \{[^}]*outline: 2px solid transparent;[^}]*transition: transform var\(--motion-control\)/, 'preset folders must own the same detached hover outline and motion as All Tags');
assert.match(styleSource, /\.preset-row:has\(\.preset-select:active\) \{ transform: translateY\(1px\) scale\(\.985\); \}/, 'preset folder click feedback must animate the whole folder shell');
assert.match(styleSource, /\.preset-row:hover:not\(:focus-within\):not\(:has\(\.preset-select:active\)\)[^}]*outline-color:[^}]*box-shadow:[^}]*translateY\(-1px\)/, 'preset folder hover must mirror the All Tags detached outline and lift');
assert.match(styleSource, /\.preset-row-top \.preset-select \{ grid-column: 1 \/ -1; grid-row: 1;[^}]*padding-right: 76px;[^}]*cursor: pointer;/, 'the preset select button must cover the complete folder row');
assert.match(styleSource, /\.preset-actions \{[^}]*grid-column: 2;[^}]*pointer-events: none;/); assert.match(styleSource, /\.preset-actions button \{ pointer-events: auto; \}/); assert.match(styleSource, /\.preset-check \{[^}]*grid-column: 3;[^}]*pointer-events: none;/, 'only real folder action buttons may intercept the full-row select target');
assert.match(electronSource, /version: 3/);
assert.match(electronSource, /savedLibrary/);
assert.match(electronSource, /nai-library/);
assert.match(electronSource, /library:image-save/);
assert.match(electronSource, /library:image-delete/);
assert.match(preloadSource, /saveLibraryImage/);
assert.match(preloadSource, /deleteLibraryImage/);
assert.match(appPathsSource, /savedLibraryDir/);
assert.match(indexSource, /raspberry-rose/);
assert.match(indexSource, /noir/);
assert.match(indexSource, /app-icon\.png/);
assert.match(iconPreparationSource, /build\/icon\.ico|icon\.ico/);
assert.match(iconPreparationSource, /prepare-icon\.ps1/);
assert.match(iconResizeSource, /HighQualityBicubic/);
assert.match(installerBuildSource, /win32icon/);
assert.match(packageSource.build.win.icon, /build\/icon\.ico/);
assert.equal(mixOrbitLayout(13, 4).placements.length, 8);
const threeAnchorNine = mixOrbitLayout(9, 3);
assert.equal(threeAnchorNine.placements.length, 9);
assert.equal(new Set(threeAnchorNine.placements.map(item => `${item.x}:${item.y}`)).size, 9);
assert.equal(mixOrbitLayout(13, 4).placements.every(item => item.box.left >= 0 && item.box.top >= 0 && item.box.left + item.box.width <= 1100 && item.box.top + item.box.height <= mixOrbitLayout(13, 4).height), true);
assert.equal(mixOrbitLayout(13, 4).placements.every(item => !('duration' in item) && !('direction' in item) && !('delay' in item)), true);
const mixCardSource = uiSource.match(/function mixArtistCardMarkup\([\s\S]*?\n\}/)?.[0] ?? '';
assert.doesNotMatch(mixCardSource, /<code/);
assert.match(styleSource, /R3 artist mix geometry/);
assert.match(styleSource, /@media \(min-width: 901px\)[\s\S]*?\.mix-orbit \{ min-height: 0; \}/);
assert.match(styleSource, /\.mix-orbit-primary \{ max-width: min\(52%, 560px\); \}/);
assert.doesNotMatch(styleSource, /@media \(max-width: 900px\)[\s\S]*?\.mix-orbit \{ display: grid;/);
assert.doesNotMatch(styleSource, /\.mix-orbit\[data-layout-ready="false"\] \.mix-orbit-slot \{ visibility: hidden; \}/);
assert.match(styleSource, /\.mix-anchor-group \{ flex-wrap: wrap; gap: 4px; max-width: 100%;/);
assert.match(uiSource, /requestAnimationFrame\(\(\) => \{[\s\S]*?requestAnimationFrame\(\(\) => \{/);
assert.match(uiSource, /new ResizeObserver\(\(\) => scheduleMixOrbitThreads\(\)\)/);
assert.match(uiSource, /setTimeout\(settle, 40\)/);
assert.match(styleSource, /\.workspace-tabs \{[^}]*max-width: 100%;[^}]*overflow-x: auto;/);
assert.match(uiSource, /saveCustomTagPresets\(customTagPresets\)/);
assert.match(previewSource, /data-artist-preview-message/);
assert.match(previewSource, /previewImage\.removeAttribute\('src'\);[\s\S]*?previewImage\.alt = '';/);
assert.match(previewSource, /function restartPreviewReveal\(host: HTMLElement\): void \{[\s\S]*?host\.classList\.remove\('is-visible'\);[\s\S]*?void host\.offsetWidth;[\s\S]*?host\.classList\.add\('is-visible'\);/);
assert.match(previewSource, /updatePosition\(target, host\);\s+host\.setAttribute\('aria-hidden', 'false'\);\s+restartPreviewReveal\(host\);/);
assert.match(uiSource, /role="tablist"/);
assert.match(uiSource, /Image Metadata/);
assert.match(uiSource, /function currentDraft\(\): PromptDraft \{[\s\S]*?animationMode \}/);
assert.match(uiSource, /function animationModeMarkup\(\): string \{[\s\S]*?Animations[\s\S]*?value="auto"[\s\S]*?value="on"[\s\S]*?value="off"/);
assert.equal((uiSource.match(/\$\{animationModeMarkup\(\)\}/g) ?? []).length, 1);
assert.match(uiSource, /<div class="top-actions">\$\{animationModeMarkup\(\)\}\$\{activeWorkspace === 'prompt'/);
assert.match(uiSource, /id="animation-mode" aria-labelledby="animation-mode-label"/);
assert.match(uiSource, /document\.documentElement\.dataset\.animationMode = mode/);
assert.match(uiSource, /#animation-mode[^\n]*addEventListener\('change'/);
assert.match(uiSource, /animationMode = normalizeAnimationMode\([\s\S]*?applyAnimationMode\(animationMode\);\s+saveDraft\(currentDraft\(\)\);/);
assert.doesNotMatch(uiSource.match(/#animation-mode[^\n]*addEventListener\('change'[\s\S]*?\n  \}\);/)?.[0] ?? '', /render\(\)/);
assert.match(uiSource, /saveDraft\(currentDraft\(\)\);/);
assert.match(uiSource, /const draft = currentDraft\(\); saveDraft\(draft\); window\.naiStorage\?\.saveSync\('draft', draft\)/);
const resetSource = uiSource.match(/function resetPrompt\(\): void \{[\s\S]*?\n\}/)?.[0] ?? '';
assert.doesNotMatch(resetSource, /animationMode\s*=/);
assert.match(uiSource, /let pendingWorkspaceTransition: 'prompt' \| 'custom-tags' \| 'metadata' \| null = null;/);
assert.match(uiSource, /function switchWorkspace\(workspace: 'prompt' \| 'custom-tags' \| 'metadata'\): void \{\s+if \(workspace === activeWorkspace\) return;\s+activeWorkspace = workspace;\s+pendingWorkspaceTransition = workspace;\s+render\(\);\s+\}/);
assert.doesNotMatch(uiSource, /Compatibility marker|function switchWorkspace\(workspace: 'prompt' \| 'metadata'\)/);
assert.match(uiSource, /function refreshConstructorGrid\(\): void \{[\s\S]*?clearArtistCardPreview\(\);[\s\S]*?grid\.innerHTML/);
const constructorFolderToggleSource = uiSource.match(/function toggleConstructorFolder\(folderId: string, button\?: HTMLButtonElement\): void \{[\s\S]*?\n\}/)?.[0] ?? '';
assert.match(constructorFolderToggleSource, /shell\.classList\.toggle\('is-open', open\)/);
assert.match(constructorFolderToggleSource, /reveal\.toggleAttribute\('inert', !open\)/);
assert.match(constructorFolderToggleSource, /warmConstructorImages\(reveal, true\)/);
assert.doesNotMatch(constructorFolderToggleSource, /refreshConstructorGrid\(\);\s*\}/);
assert.match(uiSource, /class="constructor-folder-reveal"[\s\S]*?aria-hidden="\$\{!open\}"[\s\S]*?inert/);
assert.match(uiSource, /data-constructor-image-src=.*?decoding="async"/);
assert.match(uiSource, /const CONSTRUCTOR_IMAGE_CONCURRENCY = 6;/);
assert.match(uiSource, /function startConstructorImageWarmup\(\): void \{[\s\S]*?requestAnimationFrame[\s\S]*?warmConstructorImages\(grid\)/);
assert.match(uiSource, /function warmConstructorImages\(scope: ParentNode, priority = false\): void \{[\s\S]*?img\[data-constructor-image-src\][\s\S]*?queueConstructorImage\(image, priority\)/);
assert.match(uiSource, /function pumpConstructorImageWarmup\(\): void \{[\s\S]*?PreviewCache owns the shared foreground\/background worker limits/);
assert.match(uiSource, /function openConstructor\([\s\S]*?render\(\);\s+startConstructorImageWarmup\(\);/);
assert.match(uiSource, /function closeConstructor\(\): void \{\s+clearConstructorImageWarmup\(\);/);
assert.match(uiSource, /type ConstructorTarget =/);
assert.match(uiSource, /kind: 'base'; zone: ConstructorZone/);
assert.match(uiSource, /kind: 'character'; characterId: string/);
assert.match(uiSource, /data-open-character-constructor/);
assert.match(uiSource, /function characterConstructorCards\(characterId: string\)[\s\S]*?zone === 'character'/);
assert.match(uiSource, /function constructorTargetPrompt\(target: ConstructorTarget\)[\s\S]*?characterId[\s\S]*?character\.prompt/);
assert.match(uiSource, /function setConstructorTargetPrompt\(target: ConstructorTarget[\s\S]*?character\.prompt = value/);
assert.match(uiSource, /function constructorFolderViews\(target: ConstructorTarget\)[\s\S]*?builtin:hothottuk/);
assert.match(uiSource, /function refreshConstructorGrid\(\): void \{[\s\S]*?warmConstructorImages\(grid\)/);
assert.match(uiSource, /data-constructor-tag.*toggleConstructorCard\(button\.dataset\.constructorTag!, event\)/);
assert.match(uiSource, /function refreshConstructorGrid\(options: \{ restoreFocus\?: boolean \} = \{\}\): void/);
assert.match(uiSource, /clearArtistCardPreview\(\);[\s\S]*?refreshConstructorGrid\(\{ restoreFocus: !pointerActivation \}\)/);
assert.match(styleSource, /\.constructor-folder-reveal \{[\s\S]*?grid-template-rows: 0fr[\s\S]*?transition:/);
assert.match(styleSource, /\.constructor-folder\.is-open \.constructor-folder-reveal \{ grid-template-rows: 1fr/);
assert.match(styleSource, /\.constructor-card-image img\.is-loaded \{ opacity: 1; \}/);
assert.match(uiSource, /function restoreConstructorGridFocus\(target: string \| null\): void \{[\s\S]*?target\.startsWith\('folder:'\)[\s\S]*?target\.slice\('folder:'\.length\)/);
assert.doesNotMatch(uiSource, /target\.split\(':', 2\)/);
assert.match(uiSource, /function revokeCustomImageUrl\(key: string\): void \{[\s\S]*?URL\.revokeObjectURL\(url\)/);
assert.match(uiSource, /function setCustomImageUrl\(key: string, url: string\): void \{[\s\S]*?revokeCustomImageUrl\(key\)/);
assert.match(uiSource, /class="\$\{workspacePanelClass\('prompt'\)\}"/);
assert.match(uiSource, /class="\$\{workspacePanelClass\('metadata'\)\}"/);
assert.match(uiSource, /id="artist-mix-panel" class="\$\{workspacePanelClass\('artist-mix'\)\} artist-mix-workspace/);
assert.match(savedLibraryWorkspaceSource, /id="saved-library-panel"/);
assert.match(uiSource, /id="settings-panel" class="\$\{workspacePanelClass\('settings'\)\} settings-workspace/);
assert.match(uiSource, /pendingWorkspaceTransition = null;\s+bindEvents\(\);/);
assert.ok(uiSource.includes('class="app-chrome"'), 'topbar and workspace tabs must share app chrome');
assert.match(styleSource, /\.app-chrome \{[^}]*position: sticky;[^}]*top: 0;[^}]*background: var\(--bg-deep\)/);
assert.match(styleSource, /\.app-chrome \{[^}]*isolation: isolate/);
assert.match(metadataWorkspaceSource, /class="metadata-tag-folder-arrow" aria-hidden="true"><\/span>/);
assert.match(styleSource, /\.metadata-tag-folder-arrow \{[^}]*position: absolute;[^}]*top: 50%;[^}]*right: 12px/);
assert.match(styleSource, /\.metadata-tag-folder-arrow \{[^}]*transform: translateY\(-50%\)/);
assert.match(uiSource, /data-save-character="\$\{escapeHtml\(character\.id\)\}"/);
assert.match(uiSource, /openLibrarySaveModal\('character', 'prompt-builder', character\)/);
assert.match(uiSource, /libraryFormName = character\?\.label \?\? ''/);
assert.match(uiSource, /positive: character\.prompt, negative: character\.undesired/);
assert.match(uiSource, /routeDelegatedShellAction[\s\S]*?switchWorkspace\(workspace\)/);
assert.match(uiSource, /id="full-prompt-output"/);
assert.match(uiSource, /id="artist-prompt-output"/);
assert.match(uiSource, /id="copy-prompt"/);
assert.equal((uiSource.match(/>Copy prompt</g) ?? []).length, 1);
assert.doesNotMatch(uiSource, /copy-prompt-bottom|Offline catalog|offline snapshot/);
const footerMarkup = uiSource.match(/<footer class="app-footer">[\s\S]*?<\/footer>/)?.[0] ?? '';
assert.match(footerMarkup, /class="footer-brand"><span>NAI Prompt Studio<\/span><span class="footer-links">[\s\S]*?https:\/\/nax\.moe\/\?gallery=danbooru-artist-tags-2-v5[\s\S]*?NAX · CC BY 4\.0[\s\S]*?https:\/\/hothottuk\.neocities\.org\/en[\s\S]*?hothottuk's guide/);
const customWorkspaceSource = customTagsWorkspaceSource;
assert.match(customWorkspaceSource, /custom-preset-sidebar[\s\S]*?custom-tag-form[\s\S]*?custom-tag-library/);
assert.doesNotMatch(customWorkspaceSource, /Personal images|source-note/);
assert.match(customWorkspaceSource, /role="alert"[\s\S]*?warning/);
assert.match(uiSource, /const accordionOpenState: Record<Zone, boolean> = \{ frame: true, scene: true, render: true, undesired: false \};/);
assert.match(uiSource, /function snapshotAccordionState\(\): void \{[\s\S]*?details\.open[\s\S]*?\}/);
assert.match(uiSource, /\.accordion\[data-zone\][\s\S]*?addEventListener\('toggle'/);
assert.match(uiSource, /function manualEditor\([\s\S]*?class="manual-editor"[\s\S]*?class="prompt-editor-toolbar"/);
assert.doesNotMatch(uiSource, /accordion-actions/);
assert.doesNotMatch(styleSource, /accordion-actions/);
assert.match(uiSource, /for="\$\{editorId\}"/);
assert.match(uiSource, /data-open-constructor="\$\{zone\}"/);
for (const zone of ['frame', 'scene', 'render']) assert.match(uiSource, new RegExp(`manualEditor\\('${zone}'`));
assert.match(customWorkspaceSource, /id="custom-card-kind"/);
assert.match(customWorkspaceSource, /CustomTagFilter\[\] = \['all','artist','frame','scene','render','character'\]/);
assert.match(customTagsWorkspaceSource, /class CustomTagsWorkspaceModule/);
assert.match(uiSource, /kind === 'artist' \? artistDisplayName\(rawTag\) : rawTag/);
assert.match(uiSource, /customArtistCatalogId\(item\.id\)/);
assert.match(uiSource, /rebuildEffectiveArtistCatalog\(\)/);
assert.match(uiSource, /function customArtistSignature\(tags: readonly CustomTag\[\]\): string/);
assert.match(uiSource, /if \(nextArtistSignature !== appliedCustomArtistSignature\) \{[\s\S]*?rebuildEffectiveArtistCatalog\(\);/);
assert.doesNotMatch(uiSource, /No image selected/);
assert.doesNotMatch(uiSource, /Tag group and constructor are required/);
assert.match(uiSource, /Tag and constructor are required/);
assert.match(customWorkspaceSource, /custom-image-preview is-loaded[\s\S]*?custom-image-preview is-empty/);
assert.match(uiSource, /classList\.add\('has-image'\)/);
assert.match(styleSource, /custom-image-preview\.is-loaded[\s\S]*?object-fit: contain/);
assert.match(styleSource, /custom-library-card > img \{[^}]*object-fit: contain/);
assert.match(customTagsWorkspaceSource, /selected && !isDefault[\s\S]*?data-rename-preset[\s\S]*?data-delete-preset/);
assert.match(customTagsWorkspaceSource, /preset-action-icon[\s\S]*?aria-label="Rename/);
assert.match(customTagsWorkspaceSource, /preset-action-icon[\s\S]*?aria-label="Delete/);
assert.match(styleSource, /custom-preset-list \{[^}]*padding: 6px 9px 7px 3px/);
assert.match(styleSource, /custom-save-button, \.custom-library-actions \.tiny-copy[\s\S]*?border-radius: 999px/);
assert.match(styleSource, /\.reroll-weight, \.reroll-action \{[^}]*border-radius: 999px/);
assert.match(styleSource, /html, body, \* \{ scrollbar-color/);
assert.match(styleSource, /\*::-webkit-scrollbar-thumb/);
assert.match(uiSource, /class="number-stepper"/);
assert.match(uiSource, /data-number-step="up"[\s\S]*?data-number-step="down"/);
assert.match(uiSource, /input\.stepUp\(\)[\s\S]*?input\.stepDown\(\)[\s\S]*?new Event\('input', \{ bubbles: true \}\)/);
assert.match(uiSource, /button\.disabled = input\.disabled/);
assert.match(uiSource, /button\.addEventListener\('pointerdown', event => event\.preventDefault\(\)/);
assert.match(styleSource, /input\[type="number"\]::\-webkit-inner-spin-button[\s\S]*?appearance: none/);
assert.equal((uiSource.match(/>Reset prompt</g) ?? []).length, 1);
assert.match(uiSource, /class="reset-prompt" id="reset" type="button">Reset prompt/);
assert.doesNotMatch(uiSource, /reset-footer|New prompt|Local image analysis/);
assert.match(styleSource, /\.reset-prompt \{[^}]*border: 1px solid var\(--danger\)[^}]*white-space: nowrap/);
assert.match(styleSource, /\.reset-prompt:hover/);
for (const controlId of ['copy-prompt', 'copy-artists', 'reroll-all-weights', 'random-artists', 'random-favorites-only', 'reset', 'add-character', 'open-character-picker', 'open-artist-picker', 'open-artist-picker-empty']) {
  assert.match(uiSource, new RegExp(`id="${controlId}"`));
}
assert.match(styleSource, /\.empty-artist-card:hover/);
assert.match(styleSource, /\.empty-artist-card:active/);
assert.match(styleSource, /\.empty-artist-card:focus-visible/);
assert.match(styleSource, /\.empty-artist-card:hover(?:\:not\(:active\))? img/);
assert.match(styleSource, /\.workspace-tabs button:hover/);
assert.match(styleSource, /\.workspace-tabs button:active/);
assert.match(styleSource, /\.workspace-tabs button:focus-visible/);
assert.match(styleSource, /\.primary, \.secondary,[\s\S]*?outline: 2px solid transparent;\s+outline-offset: 3px;[\s\S]*?outline-color var\(--motion-control\)/);
assert.match(styleSource, /--detached-outline-clearance: 12px/);
for (const detachedGroup of ['top-actions', 'picker-tools', 'random-actions', 'character-entry-actions', 'character-actions', 'workspace-tabs']) {
  assert.match(styleSource, new RegExp(`\\.${detachedGroup} \\{[^}]*gap: var\\(--detached-outline-clearance\\)`));
}
assert.match(styleSource, /\.subheading > div \{[^}]*gap: var\(--detached-outline-clearance\)/);
assert.match(styleSource, /\.metadata-toggle button \{[^}]*outline-offset: -2px/);
assert.match(styleSource, /\.primary:hover:not\(:active\):not\(:disabled\):not\(:focus-visible\)[\s\S]*?border-color: var\(--accent\)[\s\S]*?outline-color: rgb\(var\(--accent-bright-rgb\) \/ 88%\)[\s\S]*?box-shadow: 0 0 20px rgb\(var\(--accent-rgb\) \/ 34%\), 0 5px 14px/);
assert.match(styleSource, /\.reset-prompt:hover:not\(:active\):not\(:disabled\):not\(:focus-visible\)[\s\S]*?border-color: var\(--danger\)[\s\S]*?outline-color: rgb\(228 155 157 \/ 88%\)[\s\S]*?0 0 20px rgb\(228 155 157 \/ 30%\)/);
assert.match(styleSource, /\.primary:disabled:hover[\s\S]*?\.metadata-copy:disabled:hover \{ box-shadow: none; transform: none; \}/);
assert.match(styleSource, /\.primary:active[\s\S]*?\.secondary:active[\s\S]*?\.chip:active/);
assert.match(styleSource, /button:disabled \{[^}]*transition: none; transform: none;/);
assert.match(styleSource, /\.workspace-panel-incoming \{ animation: workspace-panel-incoming 220ms/);
const panelKeyframe = styleSource.match(/@keyframes workspace-panel-incoming \{([\s\S]*?)\n\}/)?.[1] ?? '';
assert.match(panelKeyframe, /opacity/);
assert.match(panelKeyframe, /transform/);
assert.doesNotMatch(panelKeyframe, /(?:width|height|margin|padding|left|top|right|bottom)\s*:/);
assert.doesNotMatch(styleSource, /transition\s*:\s*all\b/);
assert.match(styleSource, /\.metadata-workspace \{ max-width: 1120px;/);
assert.match(uiSource, /promptWorkspaceModule\.updateOutputs\(workspaceController, prompt\(\), buildArtistsPrompt\(base\.artists\)\)/);
assert.match(uiSource, /min="0\.1" max="2" step="0\.1"/);
assert.match(uiSource, /random-favorites-only/);
assert.match(uiSource, /resolveRandomPoolRange/);
assert.match(uiSource, /needs at least 2 favorited V5 artists/);
assert.match(uiSource, /controlMax = activeRange\.feasible \? Math\.min\(MAX_PROMPT_RANDOM_ARTISTS, activeRange\.available\)/);
assert.match(uiSource, /resolveRandomPoolRange\(requested, promptArtistPoolSize\(pool\.length\)\)/);
assert.doesNotMatch(uiSource, /Favorites pool \(\$\{artistFavorites\.size\}\)/);
assert.match(uiSource, /reroll-all-weights/);
assert.match(uiSource, /data-reroll-weight/);
assert.doesNotMatch(uiSource, /card\.png|card-overlay/);
assert.doesNotMatch(styleSource, /card\.png|card-overlay/);
assert.match(uiSource, /character-picker-backdrop/);
assert.match(uiSource, /character-previous/);
assert.match(uiSource, /character-next/);
assert.match(uiSource, /paginateCharacters/);
assert.match(uiSource, /paginateArtists/);
assert.doesNotMatch(uiSource, /slice\(0, 40\)/);
assert.doesNotMatch(uiSource, /slice\(0,\s*240\)/);
assert.match(uiSource, /artist-previous/);
assert.match(uiSource, /artist-next/);
assert.match(uiSource, /toggleFavorite\(button\.dataset\.favoriteArtist!, 'artists', true\)/);
assert.match(uiSource, /let renderedWorkspace: 'prompt' \| 'artist-mix' \| 'saved-library' \| 'custom-tags' \| 'metadata' \| 'settings' = activeWorkspace;/);
assert.match(uiSource, /workspaceScrollTop\.set\(renderedWorkspace, window\.scrollY\)/);
assert.match(uiSource, /if \(workspaceScrollTop\.has\(activeWorkspace\)\) window\.scrollTo\(\{ top: workspaceScrollTop\.get\(activeWorkspace\)!, behavior: 'auto' \}\)/);
assert.match(uiSource, /viewScrollTop\.get\(grid\.id\)/);
assert.match(customTagsWorkspaceSource, /id="custom-tag-grid"/);
assert.match(uiSource, /favoriteButton\?\.focus\(\{ preventScroll: true \}\);/);
assert.match(uiSource, /mix-artist-previous/);
assert.match(uiSource, /mix-artist-next/);
assert.match(uiSource, /mixOrbitMarkup/);
assert.doesNotMatch(uiSource, /<svg[^>]*mix-orbit/);
assert.match(uiSource, /class="mix-orbit-carrier"><div class="mix-orbit-connector"/);
assert.match(uiSource, /slot\.dataset\.orbitRow = placement\.row/);
assert.match(uiSource, /--mix-weight-scale/);
assert.match(uiSource, /--orbit-x/);
assert.match(uiSource, /--orbit-y/);
assert.match(uiSource, /function layoutMixOrbitThreads\(\)/);
assert.match(uiSource, /rectangleEdge\(anchorRect, cardCenter\.x, cardCenter\.y\)/);
assert.match(uiSource, /function commitArtistMix\(/);
assert.match(uiSource, /commitArtistMix\(nextMix, notice\);/);
assert.match(uiSource, /function mixMotionEnabled\(\)/);
assert.match(uiSource, /mixTransitionActive/);
assert.match(uiSource, /mixTransitionTimer/);
assert.match(uiSource, /disabled aria-busy="true"/);
assert.match(uiSource, /--mix-slot-index/);
assert.match(uiSource, /character-search/);
assert.match(uiSource, /classList\.toggle\('on', characterFavoritesOnly\)/);
assert.match(uiSource, /setAttribute\('aria-pressed', String\(characterFavoritesOnly\)\)/);
const characterListSource = uiSource.match(/function renderCharacterList\(\): void \{[\s\S]*?\n\}\n\nfunction refreshCharacterPicker/)?.[0] ?? '';
assert.equal((characterListSource.match(/bindCharacterBlockEvents\(\)/g) ?? []).length, 1);
assert.doesNotMatch(characterListSource, /data-character-name|data-copy-character|data-remove-character|data-character-details/);
assert.match(styleSource, /artist-card-preview/);
assert.match(styleSource, /height: min\(68vh, 520px\)/);
assert.doesNotMatch(previewSource, /window\.addEventListener\(['"]scroll['"]/);
assert.match(previewSource, /export function clearArtistCardPreview\(\): void/);
assert.match(previewSource, /activeByPointer = false;\s+activeByFocus = false;\s+activeTarget = null;/);
assert.match(previewSource, /let rangePointerFocusPending = false;/);
assert.match(previewSource, /event\.target instanceof HTMLInputElement && event\.target\.type === 'range'/);
assert.match(previewSource, /target\.addEventListener\('pointerdown',[\s\S]*?rangePointerFocusPending = true;[\s\S]*?activeByFocus = false;/);
assert.match(previewSource, /target\.addEventListener\('pointerup', finishRangePointer, true\);/);
assert.match(previewSource, /target\.addEventListener\('pointercancel', finishRangePointer, true\);/);
assert.match(previewSource, /target\.addEventListener\('lostpointercapture', finishRangePointer, true\);/);
assert.match(previewSource, /const pointerOriginatedRangeFocus = rangePointerFocusPending;\s+rangePointerFocusPending = false;\s+if \(pointerOriginatedRangeFocus\) return;/);
assert.match(previewSource, /if \(activeTarget && !activeTarget\.isConnected\) \{\s+clearArtistCardPreview\(\);/);
assert.match(uiSource, /import \{ bindArtistCardPreview, clearArtistCardPreview \} from '\.\/artist-card-preview';/);
const renderSource = uiSource.match(/function render\(\): void \{[\s\S]*?\n\}/)?.[0] ?? '';
assert.match(renderSource, /if \(!app\) return;\s+document\.documentElement\.dataset\.workspace = activeWorkspace;\s+clearHoverPreviewCache\(\);\s+updatePreviewLeases\('prompt'\);/);
assert.match(styleSource, /select:focus-visible/);
assert.match(styleSource, /\.animation-setting select \{[^}]*background: var\(--bg-deep\)[^}]*color: var\(--ink\)/);
assert.match(styleSource, /prefers-reduced-motion/);
assert.match(styleSource, /:root:not\(\[data-animation-mode="on"\]\) \.workspace-panel-incoming \{ animation: none !important; opacity: 1 !important; transform: none !important; \}/);
assert.match(styleSource, /:root:not\(\[data-animation-mode="on"\]\) \.empty-artist-card, :root:not\(\[data-animation-mode="on"\]\) \.empty-artist-card img \{ animation: none !important; transition: none !important; transform: none !important; \}/);
assert.match(styleSource, /:root:not\(\[data-animation-mode="on"\]\) \.artist-card-preview \{ opacity: 0; transition: none !important; transform: none !important; \}/);
assert.match(styleSource, /:root\[data-animation-mode="off"\] \*\{?[^\n]*animation-duration: \.001ms !important/);
assert.match(styleSource, /:root\[data-animation-mode="off"\] \.workspace-panel-incoming \{ animation: none !important; opacity: 1 !important; transform: none !important; \}/);
assert.match(styleSource, /\.workspace-panel-incoming-metadata \{ animation: workspace-panel-metadata-incoming/);
assert.match(styleSource, /@keyframes workspace-panel-metadata-incoming \{\s+from \{ opacity: 0; \}\s+to \{ opacity: 1; \}/);
assert.match(styleSource, /:root\[data-animation-mode="off"\] \.artist-card-preview\.is-visible \{ opacity: 1; transform: none !important; \}/);
assert.doesNotMatch(uiSource, /[—–]/);
assert.doesNotMatch(indexSource, /[—–]/);
assert.match(uiSource, /const existingProfileAtStartup = hasExistingProfile\(\);/);
assert.match(uiSource, /const candidates = replay \|\| !existingProfileAtStartup \? overview : update;/);
assert.match(uiSource, /overview-mix[\s\S]*?overview-saved-library[\s\S]*?overview-custom/);
assert.match(uiSource, /function openStudioAfterStartup\(\): void \{[\s\S]*?startGuide\(false\);/);
assert.doesNotMatch(uiSource.match(/function openStudioAfterStartup\(\): void \{[\s\S]*?\n\}/)?.[0] ?? '', /lastSeenVersion !== APP_VERSION/);
const restorePromptSource = uiSource.match(/if \(item\.kind === 'prompt' && item\.snapshot\) \{[\s\S]*?\n  \} else if \(item\.kind === 'artist-mix'/)?.[0] ?? '';
assert.doesNotMatch(restorePromptSource, /animationMode|applyAnimationMode|settings =/);
assert.match(storageSource, /export function hasExistingProfile\(\): boolean/);
assert.doesNotMatch(styleSource, /rgb\((?:201 168 106|229 201 141|113 75 38|98 72 130)\s*\//);
assert.doesNotMatch(uiSource, /quick\s*start|prewarm/i);
assert.match(styleSource, /:focus-visible/);
assert.match(styleSource, /:focus-within/);
assert.doesNotMatch(styleSource, /scale\(1\.32\)/);
assert.match(styleSource, /scroll-padding: 72px/);
assert.match(styleSource, /\.modal-backdrop\[hidden\] \{ display: none; \}/);
assert.match(styleSource, /\.artist-catalog-picker \.artist-catalog-grid \{[^}]*overflow-y: auto;[^}]*scrollbar-gutter: stable;/);
assert.match(styleSource, /\.mix-orbit-primary, \.mix-orbit-slot \{ position: absolute;/);
assert.match(styleSource, /\.mix-artist-card\.mix-primary \{ width: 182px;/);
assert.match(styleSource, /\.mix-artist-card \{ width: 122px;/);
assert.match(styleSource, /\.mix-orbit-carrier \{ position: absolute; inset: 0; \}/);
assert.match(styleSource, /\.mix-orbit-upright \{[^}]*left: var\(--orbit-x\);[^}]*top: var\(--orbit-y\)/);
assert.match(styleSource, /\.mix-orbit-connector \{[^}]*width: 0;/);
assert.doesNotMatch(styleSource, /mix-orbit-carrier-spin|mix-orbit-upright-spin|mix-satellite-arrive|mix-card-arrive|mix-satellite-depart|mix-card-depart|mix-thread-reveal|is-departing|is-incoming/);
assert.doesNotMatch(styleSource, /--orbit-distance|--orbit-radius|--orbit-angle/);
assert.doesNotMatch(styleSource, /mix-orbit-threads|mix-orbit-thread-spin/);
assert.doesNotMatch(styleSource, /stroke-dash(?:offset|array)/);
assert.match(styleSource, /prefers-reduced-transparency/);
assert.match(styleSource, /@media \(max-width: 760px\)/);
assert.match(styleSource, /\.selected-artist-grid \{ max-width: 100%; margin: 0; padding: 24px 12px; \}/);
assert.match(electronSource, /showErrorBox/);
assert.match(electronSource, /Menu\.setApplicationMenu\(null\)/);
assert.match(electronSource, /window\.removeMenu\(\)/);
assert.match(electronSource, /will-navigate/);
assert.match(electronSource, /No system profile fallback was used/);
assert.equal(packageSource.version, '0.6.7');
assert.equal(lockSource.version, packageSource.version);
assert.equal(lockSource.packages[''].version, packageSource.version);
assert.match(uiSource, /const APP_VERSION = '0\.6\.7'/);
assert.match(uiSource, /function bindPreviewFade\(scope: ParentNode = document\): void \{[\s\S]*?scope\.querySelectorAll<HTMLImageElement>\('\.card-image img:first-of-type, \.character-catalog-card \.preview-image'\)/);
const previewFadeSource = uiSource.match(/function bindPreviewFade\([\s\S]*?\n\}/)?.[0] ?? '';
assert.match(previewFadeSource, /image\.classList\.add\('is-decoded'\)/);
assert.match(previewFadeSource, /image\.parentElement/);
assert.match(previewFadeSource, /is-preview-ready/);
assert.match(previewFadeSource, /typeof HTMLElement !== 'undefined' && thumbnail instanceof HTMLElement/);
assert.match(previewFadeSource, /image\.complete && image\.naturalWidth > 0/);
assert.match(previewFadeSource, /image\.addEventListener\('load', markReady, \{ once: true \}\)/);
const characterPickSource = uiSource.match(/function bindCharacterPickerEvents\(\): void \{[\s\S]*?\n\}\s*\nfunction refreshArtistGrid/)?.[0] ?? '';
assert.match(characterPickSource, /characters\.push\(newCharacter\(card\.tag, `girl, \$\{card\.tag\}`\)\);\s+saveSoon\(\);\s+renderCharacterList\(\);\s+focusField\('#character-search'\);/);
assert.doesNotMatch(characterPickSource, /refreshCharacterPicker\(\);/, 'picking a character must not restart the already-visible picker page');
function refreshSource(name) {
  const start = uiSource.indexOf(`function ${name}(`);
  const end = uiSource.indexOf('\nfunction ', start + 1);
  return start >= 0 ? uiSource.slice(start, end < 0 ? uiSource.length : end) : '';
}
for (const pickerRefresh of ['refreshArtistGrid', 'refreshMixPicker', 'refreshCharacterPicker']) {
  const source = refreshSource(pickerRefresh);
  assert.match(source, /\.innerHTML =/);
  assert.match(source, /bindPreviewFade\(grid\);/);
}
assert.match(uiSource, /grid\.innerHTML = page\.cards\.map\(artistCard\)\.join\('\'\)[\s\S]*?bindPreviewFade\(grid\);/);
assert.match(uiSource, /grid\.innerHTML = page\.cards\.map\(characterCard\)\.join\('\'\);[\s\S]*?bindPreviewFade\(grid\);/);
assert.match(uiSource, /grid\.innerHTML = page\.cards\.map\(card => \{[\s\S]*?bindPreviewFade\(grid\);/);
// Exercise the readiness contract with deterministic fake images. This keeps
// the regression gate behavioral even though main.ts is an application entry
// module rather than a directly importable unit.
const previewFunctionStart = uiSource.indexOf('function bindPreviewFade(');
const previewFunctionEnd = uiSource.indexOf('\n}\n\nfunction updateEditor', previewFunctionStart) + 2;
const previewFunctionForTest = uiSource.slice(previewFunctionStart, previewFunctionEnd)
  .replace(/scope: ParentNode = document/g, 'scope = document')
  .replace(/querySelectorAll<HTMLImageElement>/g, 'querySelectorAll')
  .replace(/\): void \{/g, ') {');
class PreviewTestHTMLElement {}
const bindPreviewFadeForTest = new Function('document', 'HTMLElement', `return (${previewFunctionForTest})`)(undefined, PreviewTestHTMLElement);
class PreviewTestClassList {
  constructor() { this.values = new Set(); }
  add(value) { this.values.add(value); }
  contains(value) { return this.values.has(value); }
}
class PreviewTestParent extends PreviewTestHTMLElement {
  constructor() { super(); this.classList = new PreviewTestClassList(); }
}
class PreviewTestImage {
  constructor(complete, naturalWidth, parent = new PreviewTestParent()) { this.complete = complete; this.naturalWidth = naturalWidth; this.classList = new PreviewTestClassList(); this.parentElement = parent; this.listeners = new Map(); }
  addEventListener(type, callback, options) { const entries = this.listeners.get(type) ?? []; entries.push({ callback, once: options?.once === true }); this.listeners.set(type, entries); }
  emit(type) { const entries = this.listeners.get(type) ?? []; for (const entry of [...entries]) entry.callback(); this.listeners.set(type, entries.filter(entry => !entry.once)); }
  listenerCount(type) { return (this.listeners.get(type) ?? []).length; }
}
const cachedPreview = new PreviewTestImage(true, 96);
const pendingPreview = new PreviewTestImage(false, 0);
const failedCachePreview = new PreviewTestImage(true, 0);
const unrelatedPreview = new PreviewTestImage(false, 0);
let previewSelector = '';
let previewScopeCalls = 0;
const previewGrid = { querySelectorAll(selector) { previewScopeCalls += 1; previewSelector = selector; return [cachedPreview, pendingPreview, failedCachePreview]; } };
bindPreviewFadeForTest(previewGrid);
assert.equal(previewScopeCalls, 1);
assert.equal(previewSelector, '.card-image img:first-of-type, .character-catalog-card .preview-image');
assert.equal(cachedPreview.classList.contains('is-decoded'), true);
assert.equal(cachedPreview.parentElement.classList.contains('is-preview-ready'), true);
assert.equal(cachedPreview.listenerCount('load'), 0);
assert.equal(pendingPreview.classList.contains('is-decoded'), false);
assert.equal(pendingPreview.parentElement.classList.contains('is-preview-ready'), false);
assert.equal(pendingPreview.listenerCount('load'), 1);
assert.equal(failedCachePreview.classList.contains('is-decoded'), false);
assert.equal(failedCachePreview.parentElement.classList.contains('is-preview-ready'), false);
assert.equal(failedCachePreview.listenerCount('load'), 1);
failedCachePreview.emit('error'); failedCachePreview.emit('load');
pendingPreview.naturalWidth = 96; pendingPreview.emit('load'); pendingPreview.emit('load');
assert.equal(pendingPreview.classList.contains('is-decoded'), true);
assert.equal(pendingPreview.parentElement.classList.contains('is-preview-ready'), true);
assert.equal(failedCachePreview.classList.contains('is-decoded'), false);
assert.equal(failedCachePreview.parentElement.classList.contains('is-preview-ready'), false);
assert.equal(pendingPreview.listenerCount('load'), 0);
assert.equal(failedCachePreview.listenerCount('load'), 0);
assert.equal(unrelatedPreview.classList.contains('is-decoded'), false);
const nonElementParentClassList = new PreviewTestClassList();
const nonElementParentPreview = new PreviewTestImage(true, 96, { classList: nonElementParentClassList });
bindPreviewFadeForTest({ querySelectorAll() { return [nonElementParentPreview]; } });
assert.equal(nonElementParentPreview.classList.contains('is-decoded'), true);
assert.equal(nonElementParentClassList.contains('is-preview-ready'), false);
assert.doesNotMatch(previewFunctionForTest, /setInterval|setTimeout|requestAnimationFrame/);
assert.match(styleSource, /\.card-image > img:first-of-type\.is-decoded, \.character-catalog-card \.preview-image\.is-decoded \{[^}]*opacity: 1/);
assert.match(styleSource, /\.card-image\.is-preview-ready > \.card-skeleton, \.character-catalog-card > button:first-child\.is-preview-ready > \.card-skeleton \{[^}]*display: none;[^}]*animation: none;[^}]*pointer-events: none;/);
assert.match(previewSource, /const boundTargets = new WeakSet<HTMLElement>\(\)/);
assert.match(previewSource, /root\.querySelectorAll<HTMLElement>\(PREVIEW_SELECTOR\)/);
assert.match(uiSource, /type AppUpdatePhase = 'idle' \| 'checking' \| 'available' \| 'downloading' \| 'paused' \| 'verifying' \| 'ready' \| 'installing' \| 'up-to-date' \| 'error'/);
assert.match(uiSource, /role="progressbar"/);
assert.match(uiSource, /Download update/);
assert.match(uiSource, /Resume download/);
assert.match(uiSource, /Cancel download/);
assert.match(uiSource, /Install now/);
assert.match(uiSource, /bindAppUpdateProgress/);
assert.match(uiSource, /appUpdatePhase === 'downloading' \|\| appUpdatePhase === 'verifying' \|\| appUpdatePhase === 'installing'/);
assert.match(uiSource, /Download \$\{progress\.percent\}% complete, .* of .*\./);
assert.match(uiSource, /if \(!window\.naiUpdater \|\| appUpdatePhase === 'downloading'/);
assert.doesNotMatch(uiSource, /settingsWorkspaceLegacy/);
assert.match(uiSource, /function settingsWorkspace\(\): string \{[\s\S]*?appUpdateMarkup\(browserOnly\)/);
for (const updateControlId of ['check-app-update', 'download-app-update', 'resume-app-update', 'cancel-app-update', 'install-app-update', 'download-missing-v5', 'cancel-v5-update']) {
  assert.equal((uiSource.match(new RegExp(`id="${updateControlId}"`, 'g')) ?? []).length, 1);
}
assert.doesNotMatch(uiSource, /downloadAndInstall/);
assert.doesNotMatch(electronSource, /app-update:download-install/);
assert.doesNotMatch(electronSource, /showMessageBox/);
console.log('renderer-static tests passed.');
